// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Bit's World",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Bit's World",
            targets: ["AppModule"],
            bundleIdentifier: "com.lucasfrancisco.Joguinho",
            teamIdentifier: "Q7Z5S76S2J",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources"),
                .copy("KIdDOS-Regular.ttf")
            ]
        )
    ]
)